version: '3'
services:
  db:
    image:  mysql:latest
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
  web:
    build: .
    ports:
      - "1909:1909"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
    links:
      - "db:database"   
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"